[project]
name = "docproc"
version = "0.1.0"
description = "Opinionated and Sophisticated Document Region Analyzer."
authors = [{ name = "Rithul Kamesh", email = "hi@rithul.dev" }]
readme = "README.md"
license = { file = "./LICENSE.md" }
requires-python = ">=3.12"
dependencies = ["pymupdf"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
